// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLWQpfz0zk5bV4spHioRhvLACeKkWrYeI',
    appId: '1:1071818841512:web:cc167296eb68ee5d27919d',
    messagingSenderId: '1071818841512',
    projectId: 'chattt-appp-100e9',
    authDomain: 'chattt-appp-100e9.firebaseapp.com',
    storageBucket: 'chattt-appp-100e9.firebasestorage.app',
    measurementId: 'G-RKQDY60RKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoPh_Ue5Zh2Q7k8Yk75R1t0WCgCngjMDU',
    appId: '1:1071818841512:android:cc52eb42f91f5a6027919d',
    messagingSenderId: '1071818841512',
    projectId: 'chattt-appp-100e9',
    storageBucket: 'chattt-appp-100e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz7vyCMUoYjqApJLEeTADzXXL1u4WEwvI',
    appId: '1:1071818841512:ios:7349fcf660369f6c27919d',
    messagingSenderId: '1071818841512',
    projectId: 'chattt-appp-100e9',
    storageBucket: 'chattt-appp-100e9.firebasestorage.app',
    iosBundleId: 'com.example.chattApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz7vyCMUoYjqApJLEeTADzXXL1u4WEwvI',
    appId: '1:1071818841512:ios:7349fcf660369f6c27919d',
    messagingSenderId: '1071818841512',
    projectId: 'chattt-appp-100e9',
    storageBucket: 'chattt-appp-100e9.firebasestorage.app',
    iosBundleId: 'com.example.chattApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLWQpfz0zk5bV4spHioRhvLACeKkWrYeI',
    appId: '1:1071818841512:web:0070566024423dbf27919d',
    messagingSenderId: '1071818841512',
    projectId: 'chattt-appp-100e9',
    authDomain: 'chattt-appp-100e9.firebaseapp.com',
    storageBucket: 'chattt-appp-100e9.firebasestorage.app',
    measurementId: 'G-HMBEW2P9BS',
  );
}
